language: python
cache: pip

# Use container-based infrastructure
dist: xenial
sudo: false

matrix:
  fast_finish: true
  include:
    - env: LINT=1
      python: 3.7
    - env: TOXENV=py37-django22-wagtail26
      python: 3.7
    - env: TOXENV=py37-django22-wagtail25
      python: 3.7
    - env: TOXENV=py36-django21-wagtail24
      python: 3.6
    - env: TOXENV=py36-django21-wagtail23
      python: 3.6
    - env: TOXENV=py35-django20-wagtail24
      python: 3.5
    - env: TOXENV=py35-django20-wagtail23
      python: 3.5

  allow_failures:
    - env: TOXENV=py37-djangomaster-wagtail26
    - env: TOXENV=py37-djangomaster-wagtailmaster

install:
  - if [[ $LINT ]]; then pip install wheel flake8 isort black; fi
  - if [[ $TOXENV ]]; then pip install -e .[testing]; fi

script:
  - if [[ $LINT ]]; then flake8 wagtail_headless_preview; fi
  - if [[ $LINT ]]; then isort --check-only --diff --recursive wagtail_headless_preview; fi
  - if [[ $LINT ]]; then black --check wagtail_headless_preview; fi
  - test ${TOXENV} && nohup python3 -m http.server 8020 --directory wagtail_headless_preview/tests/client > /dev/null 2>&1 &
  - if [[ $TOXENV ]]; then tox; fi
